[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]

bytes = "1.5"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }
strum = { version = "0.26", features = ["derive"] }
crossbeam-channel = "0.5"
rand = "0.9"